# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_tutorial',
                'doc_host': 'https://Tetlanesh.github.io',
                'git_url': 'https://github.com/Tetlanesh/nbdev_tutorial',
                'lib_path': 'nbdev_tutorial'},
  'syms': { 'nbdev_tutorial.core': { 'nbdev_tutorial.core.foo': ('core.html#foo', 'nbdev_tutorial/core.py'),
                                     'nbdev_tutorial.core.foo2': ('core.html#foo2', 'nbdev_tutorial/core.py')}}}